### ISSUE TITLE
eslint --init 후에 설정파일 생성시 오류가 납니다.

### ISSUE THREAD

**Issue by cerori** [bjpublic/next.js#11]
```json
{
  "name": "next-todo",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "dev": "next"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "dependencies": {
    "next": "^10.0.7",
    "react": "^17.0.1",
    "react-dom": "^17.0.1"
  },
  "devDependencies": {
    "@types/node": "^14.14.31",
    "@types/react": "^17.0.2",
    "@typescript-eslint/eslint-plugin": "^4.16.1",
    "@typescript-eslint/parser": "^4.16.1",
    "eslint": "^7.21.0",
    "eslint-config-airbnb": "^18.2.1",
    "eslint-plugin-import": "^2.22.1",
    "eslint-plugin-jsx-a11y": "^6.4.1",
    "eslint-plugin-react": "^7.22.0",
    "eslint-plugin-react-hooks": "^4.2.0",
    "typescript": "^4.2.3"
  }
}
```

```bash
Oops! Something went wrong! :(

ESLint: 7.21.0

Error: An error occurred while generating your JavaScript config file. A config file was still generated, but the config file itself may not follow your linting rules.
Error: Failed to load plugin '@typescript-eslint' declared in 'BaseConfig': Cannot find module 'eslint'
Require stack:
- D:\workspace\node\next-todo\node_modules\@typescript-eslint\experimental-utils\dist\ts-eslint\CLIEngine.js
- D:\workspace\node\next-todo\node_modules\@typescript-eslint\experimental-utils\dist\ts-eslint\index.js
- D:\workspace\node\next-todo\node_modules\@typescript-eslint\experimental-utils\dist\eslint-utils\RuleTester.js
- D:\workspace\node\next-todo\node_modules\@typescript-eslint\experimental-utils\dist\eslint-utils\index.js
- D:\workspace\node\next-todo\node_modules\@typescript-eslint\experimental-utils\dist\index.js
- D:\workspace\node\next-todo\node_modules\@typescript-eslint\eslint-plugin\dist\rules\adjacent-overload-signatures.js
- D:\workspace\node\next-todo\node_modules\@typescript-eslint\eslint-plugin\dist\rules\index.js
- D:\workspace\node\next-todo\node_modules\@typescript-eslint\eslint-plugin\dist\index.js
- C:\Users\wjdrmsl\AppData\Roaming\npm\node_modules\eslint\node_modules\@eslint\eslintrc\lib\config-array-factory.js
- C:\Users\wjdrmsl\AppData\Roaming\npm\node_modules\eslint\node_modules\@eslint\eslintrc\lib\index.js
- C:\Users\wjdrmsl\AppData\Roaming\npm\node_modules\eslint\lib\cli-engine\cli-engine.js
- C:\Users\wjdrmsl\AppData\Roaming\npm\node_modules\eslint\lib\cli-engine\index.js
- C:\Users\wjdrmsl\AppData\Roaming\npm\node_modules\eslint\lib\init\source-code-utils.js
- C:\Users\wjdrmsl\AppData\Roaming\npm\node_modules\eslint\lib\init\config-initializer.js
- C:\Users\wjdrmsl\AppData\Roaming\npm\node_modules\eslint\bin\eslint.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (C:\Users\wjdrmsl\AppData\Roaming\npm\node_modules\eslint\node_modules\v8-compile-cache\v8-compile-cache.js:159:20)
    at Object.<anonymous> (D:\workspace\node\next-todo\node_modules\@typescript-eslint\experimental-utils\dist\ts-eslint\CLIEngine.js:5:18)
    at Module._compile (C:\Users\wjdrmsl\AppData\Roaming\npm\node_modules\eslint\node_modules\v8-compile-cache\v8-compile-cache.js:192:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
```

eslint --init 
후에 설정파일 생성시 오류가 납니다.
오류가 나도 상관 없는건가요?

**Comment by asheed** [comment]
지나가던 과객입니다만...
저도 위와 동일한 오류가 발생했었는데..
원인은 서버가 동작하고 있어서 였습니다. ;;
터미넡 창에서 `ctrl+c` 로 서버를 종료시킨 후 `eslint --init` 을 재실행해 보시기 바랍니다.
